### PR TITLE
Fix unknown basetype mapping

### LINKED ISSUE #2508: Unknow base type causing empty datatype
screenshot_2018-12-10_16-12-33

And transformation (e.g. load to sandbox) will fail.

### PR DESCRIPTION
**Pull request by ujovlado**
Fixes #2508 

Proposed changes:

- unknown base type will return `null`  (identical to case w/o base type)
- properly handle `null` data type

### CODE REVIEW

File: src/scripts/modules/transformations/react/components/mapping/InputMappingRowSnowflakeEditor.jsx [hunk 1]
```diff
@@ -235,7 +235,10 @@ export default React.createClass({
 
   buildDatatypes(columns, datatypes = Map()) {
     return columns.reduce((memo, column) => {
-      return memo.set(column, datatypes.get(column, this.getDefaultDatatype(column)));
+      if (!datatypes.get(column)) {
+        return memo.set(column, this.getDefaultDatatype(column));
+      }
+      return memo.set(column, datatypes.get(column));
```
Comment (pivnicek) [inline src/scripts/modules/transformations/react/components/mapping/InputMappingRowSnowflakeEditor.jsx]: This is functionally equivalent right?

Comment (pivnicek) [reply src/scripts/modules/transformations/react/components/mapping/InputMappingRowSnowflakeEditor.jsx]: jj, uz chapu:)
